### ISSUE TITLE
v20.errors.ResponseNoField: 400 response for GET 

### ISSUE THREAD

**Issue by BenSa0112** [trentstauff/FXBot#24]
File "....\forexbot\venv\lib\site-packages\tpqoa-0.0.55-py3.9.egg\tpqoa\tpqoa.py", line 238, in get_history
  File "....\forexbot\venv\lib\site-packages\tpqoa-0.0.55-py3.9.egg\tpqoa\tpqoa.py", line 167, in retrieve_data
  File "....\forexbot\venv\lib\site-packages\v20\response.py", line 35, in get
    raise ResponseNoField(self, field)
v20.errors.ResponseNoField: 400 response for GET https://api-fxpractice.oanda.com:443/v3/instruments/EUR_USD/candles?price=M&granularity=1h&from=2022-01-01T00%3A00%3A00.000000000Z&to=2022-01-07T00%3A00%3A00.000000000Z does not have field 'candles' (contains 'errorMessage')

Any ideas what causes this error message?

**Comment by trentstauff** [comment]
Do you know what you put as the granularity value? Usually its along the format of "1hr" "1m" "5s" etc. Or is it just not working at all for you?

**Comment by trentstauff** [comment]
My bad, it says 1h right in the link. Hm. Try a different granularity and see if that works.

**Comment by BenSa0112** [comment]
I tried several. Like for example 1h, 5s etc. They don´t work at all. Maybe there is something wrong with the api keys in the .cfg file. But i checked them already.

**Comment by trentstauff** [comment]
Sounds good, ill take a look into it today

**Comment by trentstauff** [comment]
If possible, could you provide each input you gave to the command line from the time you started the session?

**Comment by BenSa0112** [comment]
Enter an instrument to trade: 

AUD_CAD, AUD_CHF, AUD_HKD, AUD_JPY, AUD_NZD, AUD_SGD, AUD_USD, AU200_AUD, BTC_USD, BCH_USD, BCO_USD, DE10YB_EUR, CAD_CHF, CAD_HKD, CAD_JPY, CAD_SGD, CHF_HKD, CHF_JPY, CHF_ZAR, CN50_USD, CHINAH_HKD, XCU_USD, CORN_USD, EUR_AUD, EUR_CAD, EUR_CHF, EUR_CZK, EUR_DKK, EUR_GBP, EUR_HKD, EUR_HUF, EUR_JPY, EUR_NOK, EUR_NZD, EUR_PLN, EUR_SEK, EUR_SGD, EUR_TRY, EUR_USD, EUR_ZAR, ETH_USD, EU50_EUR, FR40_EUR, GBP_AUD, GBP_CAD, GBP_CHF, GBP_HKD, GBP_JPY, GBP_NZD, GBP_PLN, GBP_SGD, GBP_USD, GBP_ZAR, DE30_EUR, XAU_USD, XAU_AUD, XAU_CAD, XAU_CHF, XAU_EUR, XAU_GBP, XAU_HKD, XAU_JPY, XAU_NZD, XAU_SGD, XAU_XAG, HKD_JPY, HK33_HKD, IN50_USD, JP225_USD, JP225Y_JPY, LTC_USD, NZD_CAD, NZD_CHF, NZD_HKD, NZD_JPY, NZD_SGD, NZD_USD, NATGAS_USD, NL25_EUR, XPD_USD, XPT_USD, SGD_CHF, SGD_JPY, XAG_USD, XAG_AUD, XAG_CAD, XAG_CHF, XAG_EUR, XAG_GBP, XAG_HKD, XAG_JPY, XAG_NZD, XAG_SGD, SG30_SGD, SOYBN_USD, ESPIX_EUR, SUGAR_USD, CH20_CHF, TRY_JPY, TWIX_USD, UK100_GBP, UK10YB_GBP, USB10Y_USD, USB02Y_USD, USB05Y_USD, NAS100_USD, US2000_USD, SPX500_USD, USB30Y_USD, US30_USD, USD_CAD, USD_CHF, USD_CNH, USD_CZK, USD_DKK, USD_HKD, USD_HUF, USD_INR, USD_JPY, USD_MXN, USD_NOK, USD_PLN, USD_SEK, USD_SGD, USD_THB, USD_TRY, USD_ZAR, WTICO_USD, WHEAT_USD, ZAR_JPY, 

EUR_USD
Live Trading (1) or Backtesting (2)? 
2
Please choose the strategy you would like to backtest: 

sma, bollinger_bands, contrarian, momentum, ml_classification, ml_regression, 
sma
Enter the start date for the backtest (string, in form of "YYYY-MM-DD"): 

2022-01-01
Enter the end date for the backtest (string, in form of "YYYY-MM-DD"): 

2022-01-07
Enter the trading cost to consider: (float, IE 0.0, 0.00007): 

100
Please enter the granularity for your session (IE "1h", "1m", "5s"): 

1h
Enter SMAS value (integer, IE 9): 

9
Enter SMAL value (integer, IE 20): 

20

Downloading historical data...
Traceback (most recent call last):
..........

**Comment by trentstauff** [comment]
Thanks! Okay, I believe I've found the issue. It seems like the underlaying API used to send out the request has tightened the accepted granularity inputs. Before, you could get away with "1m" and "1hr" and it would convert it to the closest API-correct parameter, but that doesnt seem to be the case now.

Heres a list of accepted granularities (I will update the readme and the default parameters/suggestions):
Please give one of these a shot and let me know if it works for you!

![image](https://user-images.githubusercontent.com/53923200/148830879-1c8392ff-1646-4389-a7ac-4ac84845d343.png)

**Comment by BenSa0112** [comment]
Thank you very much!!!

**Comment by trentstauff** [comment]
NP, currently working on a collateral bug due to the fix but backtesting should be working now. Livetrading will be good to go in a couple minutes!
