### ISSUE TITLE
TypeError: get_history() got an unexpected keyword argument 'localize'

### ISSUE THREAD

**Issue by ddomenico25** [trentstauff/FXBot#25]
https://github.com/trentstauff/FXBot/blob/33d4bc8cd422f36879a52df6da32bd3579cdaedf/livetrading/LiveTrader.py#L96

**Comment by ddomenico25** [comment]
if i try with the backtesting i get the same error -> #24

**Comment by trentstauff** [comment]
Okay, ill take a look into it today. Thanks

**Comment by trentstauff** [comment]
Hey @ddomenico25 , checkout https://github.com/trentstauff/FXBot/issues/24 if you were having a similar error.

Is the get_history error reproducible? If so, could you send me the inputs you gave to the command line to get it?

Thanks!

**Comment by ddomenico25** [comment]
I changed the granularity to the accepted ones but I have this problem:

Enter an instrument to trade:

LTC_USD, HK33_HKD, EUR_HUF, FR40_EUR, EUR_DKK, XAU_CHF, XPD_USD, BCO_USD, IN50_USD, NATGAS_USD, USD_MXN, GBP_USD, CAD_CHF, EUR_GBP, XAG_SGD, JP225_USD, XAG_CAD, CN50_USD, EU50_EUR, GBP_CHF, USD_THB, USD_ZAR, XAU_USD, XPT_USD, XAU_EUR, EUR_NOK, XCU_USD, CAD_JPY, XAU_HKD, EUR_HKD, AUD_HKD, USD_SEK, GBP_SGD, GBP_HKD, EUR_NZD, XAG_AUD, WTICO_USD, XAG_NZD, SGD_CHF, AUD_SGD, TWIX_USD, EUR_JPY, USD_CHF, USD_TRY, GBP_JPY, EUR_CZK, CHF_ZAR, BTC_USD, EUR_TRY, USD_JPY, GBP_ZAR, SGD_JPY, XAU_SGD, USD_CZK, XAU_JPY, XAG_JPY, USD_NOK, ZAR_JPY, TRY_JPY, USD_DKK, EUR_PLN, SUGAR_USD, AUD_CAD, USD_HKD, CAD_SGD, US2000_USD, DE10YB_EUR, USB02Y_USD, USB05Y_USD, USB10Y_USD, GBP_NZD, XAU_NZD, ETH_USD, NZD_USD, XAG_GBP, XAG_EUR, CORN_USD, XAG_USD, AUD_NZD, UK100_GBP, CHF_HKD, NZD_HKD, USD_CNH, XAU_GBP, SPX500_USD, NZD_SGD, JP225Y_JPY, BCH_USD, USD_SGD, EUR_SEK, ESPIX_EUR, NZD_CHF, XAU_XAG, HKD_JPY, XAG_CHF, AUD_CHF, CHF_JPY, NAS100_USD, AUD_JPY, EUR_ZAR, XAU_CAD, EUR_AUD, NZD_JPY, XAG_HKD, WHEAT_USD, XAU_AUD, USD_CAD, USD_INR, UK10YB_GBP, EUR_CHF, NL25_EUR, EUR_CAD, USD_HUF, USB30Y_USD, NZD_CAD, EUR_SGD, AUD_USD, SOYBN_USD, EUR_USD, SG30_SGD, GBP_AUD, USD_PLN, AU200_AUD, CHINAH_HKD, CH20_CHF, CAD_HKD, US30_USD, GBP_CAD, GBP_PLN, DE30_EUR,

EUR_USD
Live Trading (1) or Backtesting (2)?
1
Please choose the strategy you would like to utilize:

sma, bollinger_bands, contrarian, momentum, ml_classification,
bollinger_bands
Please enter the granularity for your session (IE "1h", "1m", "5s"):

H1
Please enter the number of units you'd like to trade with (integer, IE 200000 units):

10
Enter stop profit dollars to halt trading at (float, IE 25, 15.34, etc)  (enter "n" if not applicable):

n
Enter a negative stop loss to halt trading at (float, IE -25, -1.32, etc) (enter "n" if not applicable):

n
Enter SMA value (integer, IE 9):

9
Enter deviation value (integer, IE 2):

2
Markets are open, beginning trading session.
Traceback (most recent call last):
  File "C:\Users\Utente 1\Downloads\FXBot-main\FXBot-main\main.py", line 128, in <module>
    trader = BollingerBandsLive(cfg, instrument, granularity, sma, deviation, units, stop_loss=stop_loss,
  File "C:\Users\Utente 1\Downloads\FXBot-main\FXBot-main\livetrading\BollingerBandsLive.py", line 37, in __init__
    super().__init__(
  File "C:\Users\Utente 1\Downloads\FXBot-main\FXBot-main\livetrading\LiveTrader.py", line 52, in __init__
    self._bar_length = pd.to_timedelta(bar_length)
  File "C:\Users\Utente 1\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\tools\timedeltas.py", line 132, in to_timedelta
    return _coerce_scalar_to_timedelta_type(arg, unit=unit, errors=errors)
  File "C:\Users\Utente 1\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\tools\timedeltas.py", line 138, in _coerce_scalar_to_timedelta_type
    result = Timedelta(r, unit)
  File "pandas\_libs\tslibs\timedeltas.pyx", line 1194, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
  File "pandas\_libs\tslibs\timedeltas.pyx", line 335, in pandas._libs.tslibs.timedeltas.parse_timedelta_string
  File "pandas\_libs\tslibs\timedeltas.pyx", line 490, in pandas._libs.tslibs.timedeltas.timedelta_from_spec
ValueError: could not convert string to float: '.'
Exception ignored in: <function LiveTrader.__del__ at 0x0000026A6FC4C3A0>
Traceback (most recent call last):
  File "C:\Users\Utente 1\Downloads\FXBot-main\FXBot-main\livetrading\LiveTrader.py", line 82, in __del__
    self.close_position()
  File "C:\Users\Utente 1\Downloads\FXBot-main\FXBot-main\livetrading\LiveTrader.py", line 257, in close_position
    if self._position != 0:
AttributeError: 'BollingerBandsLive' object has no attribute '_position'

Thanks for the attention!

**Comment by trentstauff** [comment]
Kk, let me take a look

**Comment by trentstauff** [comment]
Okay, should be good to go. Please pull from main again, and try a granularity of "1hr" or "1m" (NOT listed in the screenshot). It seems like the strict granularity options are only for backtesting.

Let me know of any other errors.

**Comment by kernelhacks** [comment]
I get the tz_location error
Enter an instrument to trade: 

AUD_CAD, AUD_CHF, AUD_HKD, AUD_JPY, AUD_NZD, AUD_SGD, AUD_USD, CAD_CHF, CAD_HKD, CAD_JPY, CAD_SGD, CHF_HKD, CHF_JPY, CHF_ZAR, EUR_AUD, EUR_CAD, EUR_CHF, EUR_CZK, EUR_DKK, EUR_GBP, EUR_HKD, EUR_HUF, EUR_JPY, EUR_NOK, EUR_NZD, EUR_PLN, EUR_SEK, EUR_SGD, EUR_TRY, EUR_USD, EUR_ZAR, GBP_AUD, GBP_CAD, GBP_CHF, GBP_HKD, GBP_JPY, GBP_NZD, GBP_PLN, GBP_SGD, GBP_USD, GBP_ZAR, HKD_JPY, NZD_CAD, NZD_CHF, NZD_HKD, NZD_JPY, NZD_SGD, NZD_USD, SGD_CHF, SGD_JPY, TRY_JPY, USD_CAD, USD_CHF, USD_CNH, USD_CZK, USD_DKK, USD_HKD, USD_HUF, USD_JPY, USD_MXN, USD_NOK, USD_PLN, USD_SEK, USD_SGD, USD_THB, USD_TRY, USD_ZAR, ZAR_JPY, 

EUR_USD
Live Trading (1) or Backtesting (2)? 
2
Please choose the strategy you would like to backtest: 

sma, bollinger_bands, contrarian, momentum, ml_classification, ml_regression, 
sma
Enter the start date for the backtest (string, in form of "YYYY-MM-DD"): 

2022-04-19
Enter the end date for the backtest (string, in form of "YYYY-MM-DD"): 

2022-04-19
Enter the trading cost to consider: (float, IE 0.0, 0.00007): 

1.0811
Please enter the granularity for your session (See list in README, IE "S30", "M1", "H1"): 

H1
Enter SMAS value (integer, IE 9): 

6
Enter SMAL value (integer, IE 20): 

13
Downloading historical data...
Traceback (most recent call last):
  File "main.py", line 214, in <module>
    trader = SMABacktest(instrument, start, end, smas, smal, granularity, trading_cost)
  File "/home/darwin/FXBot/backtesting/SMABacktest.py", line 25, in __init__
    super().__init__(
  File "/home/darwin/FXBot/backtesting/Backtester.py", line 27, in __init__
    self._data = self.acquire_data()
  File "/home/darwin/FXBot/backtesting/Backtester.py", line 41, in acquire_data
    df = oanda.get_history(
  File "/home/darwin/FXBot/env/lib/python3.8/site-packages/tpqoa/tpqoa.py", line 241, in get_history
    data.index = data.index.tz_localize(None)
AttributeError: 'Index' object has no attribute 'tz_localize'
