### ISSUE TITLE
AttributeError: 'SMALive' object has no attribute '_position'

### ISSUE THREAD

**Issue by BenSa0112** [trentstauff/FXBot#26]
Markets are open, beginning trading session.

------------------------------------------------------

C:\...\forexbot\venv\lib\site-packages\pandas\core\tools\timedeltas.py:132: FutureWarning: Units 'M', 'Y' and 'y' do not represent unambiguous timedelta values and will be removed in a future version
  return _coerce_scalar_to_timedelta_type(arg, unit=unit, errors=errors)
Traceback (most recent call last):
  File "C:\...\forexbot\FXBot\main.py", line 114, in <module>
    trader = SMALive(cfg, instrument, granularity, smas, smal, units, stop_loss=stop_loss, stop_profit=stop_profit)
  File "C:\...\forexbot\FXBot\livetrading\SMALive.py", line 37, in __init__
    super().__init__(
  File "C:\...\forexbot\FXBot\livetrading\LiveTrader.py", line 52, in __init__
    self._bar_length = pd.to_timedelta(bar_length)
  File "C:\...\forexbot\venv\lib\site-packages\pandas\core\tools\timedeltas.py", line 132, in to_timedelta
    return _coerce_scalar_to_timedelta_type(arg, unit=unit, errors=errors)
  File "C:\...\forexbot\venv\lib\site-packages\pandas\core\tools\timedeltas.py", line 138, in _coerce_scalar_to_timedelta_type
    result = Timedelta(r, unit)
  File "pandas\_libs\tslibs\timedeltas.pyx", line 1194, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
  File "pandas\_libs\tslibs\timedeltas.pyx", line 335, in pandas._libs.tslibs.timedeltas.parse_timedelta_string
  File "pandas\_libs\tslibs\timedeltas.pyx", line 490, in pandas._libs.tslibs.timedeltas.timedelta_from_spec
ValueError: could not convert string to float: '.'
Exception ignored in: <function LiveTrader.__del__ at 0x00000110BDFCB9D0>
Traceback (most recent call last):
  File "C:\...\forexbot\FXBot\livetrading\LiveTrader.py", line 82, in __del__
    self.close_position()
  File "C:\...\forexbot\FXBot\livetrading\LiveTrader.py", line 257, in close_position
    if self._position != 0:
AttributeError: 'SMALive' object has no attribute '_position'

Process finished with exit code 1

-----------------------------------------------------

Hope anyone can help me with this error code?

**Comment by trentstauff** [comment]
Hey Ben, could you provide the steps to reproduce

**Comment by BenSa0112** [comment]
Of course.
----------------------------------------
AUD_CAD, AUD_CHF, AUD_HKD, AUD_JPY, AUD_NZD, AUD_SGD, AUD_USD, AU200_AUD, BTC_USD, BCH_USD, BCO_USD, DE10YB_EUR, CAD_CHF, CAD_HKD, CAD_JPY, CAD_SGD, CHF_HKD, CHF_JPY, CHF_ZAR, CN50_USD, CHINAH_HKD, XCU_USD, CORN_USD, EUR_AUD, EUR_CAD, EUR_CHF, EUR_CZK, EUR_DKK, EUR_GBP, EUR_HKD, EUR_HUF, EUR_JPY, EUR_NOK, EUR_NZD, EUR_PLN, EUR_SEK, EUR_SGD, EUR_TRY, EUR_USD, EUR_ZAR, ETH_USD, EU50_EUR, FR40_EUR, GBP_AUD, GBP_CAD, GBP_CHF, GBP_HKD, GBP_JPY, GBP_NZD, GBP_PLN, GBP_SGD, GBP_USD, GBP_ZAR, DE30_EUR, XAU_USD, XAU_AUD, XAU_CAD, XAU_CHF, XAU_EUR, XAU_GBP, XAU_HKD, XAU_JPY, XAU_NZD, XAU_SGD, XAU_XAG, HKD_JPY, HK33_HKD, IN50_USD, JP225_USD, JP225Y_JPY, LTC_USD, NZD_CAD, NZD_CHF, NZD_HKD, NZD_JPY, NZD_SGD, NZD_USD, NATGAS_USD, NL25_EUR, XPD_USD, XPT_USD, SGD_CHF, SGD_JPY, XAG_USD, XAG_AUD, XAG_CAD, XAG_CHF, XAG_EUR, XAG_GBP, XAG_HKD, XAG_JPY, XAG_NZD, XAG_SGD, SG30_SGD, SOYBN_USD, ESPIX_EUR, SUGAR_USD, CH20_CHF, TRY_JPY, TWIX_USD, UK100_GBP, UK10YB_GBP, USB10Y_USD, USB02Y_USD, USB05Y_USD, NAS100_USD, US2000_USD, SPX500_USD, USB30Y_USD, US30_USD, USD_CAD, USD_CHF, USD_CNH, USD_CZK, USD_DKK, USD_HKD, USD_HUF, USD_INR, USD_JPY, USD_MXN, USD_NOK, USD_PLN, USD_SEK, USD_SGD, USD_THB, USD_TRY, USD_ZAR, WTICO_USD, WHEAT_USD, ZAR_JPY, 

EUR_USD
Live Trading (1) or Backtesting (2)? 
1
Please choose the strategy you would like to utilize: 

sma, bollinger_bands, contrarian, momentum, ml_classification, 
sma
Please enter the granularity for your session (NOT from list in README, try "1hr", "1m", "30s" (less strict): 

M15
Please enter the number of units you'd like to trade with (integer, IE 200000 units): 

100
Enter stop profit dollars to halt trading at (float, IE 25, 15.34, etc)  (enter "n" if not applicable): 

10
Enter a negative stop loss to halt trading at (float, IE -25, -1.32, etc) (enter "n" if not applicable): 

-10
Enter SMAS value (integer, IE 9): 

9
Enter SMAL value (integer, IE 20): 

20
Markets are open, beginning trading session.
.......

**Comment by trentstauff** [comment]
Hey Ben, try "15m" for granularity when doing live trading. Sorry for the inconsistency but that should fix it.

**Comment by trentstauff** [comment]
When live trading, you dont need to follow the strict rule guide in the screenshot I posted before.

**Comment by BenSa0112** [comment]
I got it. It works pretty fine right now. Thank you very much for your support.
