### ISSUE TITLE
AttributeError: module 'tpqoa' has no attribute 'tpqoa'

### ISSUE THREAD

**Issue by kernelhacks** [trentstauff/FXBot#30]
It's show this error when I try to run the main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from livetrading.BollingerBandsLive import BollingerBandsLive
  File "/root/FXBot/livetrading/BollingerBandsLive.py", line 3, in <module>
    from livetrading.LiveTrader import LiveTrader
  File "/root/FXBot/livetrading/LiveTrader.py", line 12, in <module>
    class LiveTrader(tpqoa.tpqoa):
AttributeError: module 'tpqoa' has no attribute 'tpqoa'

**Comment by lorenzourb** [comment]
having same here..

**Comment by siteriaitaliana** [comment]
fixed with git submodule update --init --recursive and then python setup.py install in the tpqoa folder

**Comment by trentstauff** [comment]
Siteria is right. The repository relies on submodules and so you will need to execute this command to clone successfully:

`git clone --recurse-submodules -j8 https://github.com/trentstauff/FXBot`

Could someone confirm this fixes the issue? If it doesnt, I'll update the readme to have Siteria's solution.

Trent

**Comment by kernelhacks** [comment]
Confirmed, this solution work for me.

**Comment by trentstauff** [comment]
Perfect, thanks everyone!

**Comment by seguri** [comment]
Hi, the readme is still not updated, right?

**Comment by trentstauff** [comment]
Hi Seguri, the beginning of the readme has been updated in reference to the no tpqoa issue.

<img width="818" alt="image" src="https://user-images.githubusercontent.com/53923200/177198202-fe8667d9-0319-4a4c-8a40-ba5e9f52e7e0.png">
